### PR TITLE
Viite 343 viite visualation transferring floatings

### PR DESCRIPTION
**Pull request by jorgebfrr**
Viite 343 viite visualation transferring floatings
VIITE 342 Using "tab" key should move the user to next field in the form

### CODE REVIEW

**Comment by oappicgi** [comment]
Didn't visually check it with staging db (i dont think dev schema  has enough content to test it). but looks ok. I think tab thing was already solved by Jani in 239/240 branch, so it can be ignored in merge.

**Comment by jorgebfrr** [comment]
@oappicgi i didn't know that VIITE-342 was already resolve. The problem has in Mozilla Firefox only.
The visualization was made with both enviromments (Dev and Stagging). Can i have your approvement?

**Comment by oappicgi** [comment]
Looks good

Problems to be fixed in other tasks:

-Calibration point in old position
- Might not be enough to remove floating line (probably needs to keep filter list of floating links that should not be drawn until peruuta/cancel is pressed)

**Comment by tvenhola** [comment]
I got errors when trying this out with data I took from devtest and added to the fixture:
Uncaught ReferenceError: singleLinkSelect is not defined
    at Object.openUnknown (SelectedLinkProperty.js:127)
    at ol.interaction.Select.<anonymous> (LinkPropertyLayer.js:247)
    at ol.interaction.Select.b (ol3.js:49)
    at ol.interaction.Select.ol.events.EventTarget.dispatchEvent (ol3.js:53)
    at ol.interaction.Select.handleEvent (ol3.js:1704)
    at ol.Map.handleMapBrowserEvent (ol3.js:900)
    at ol.MapBrowserEventHandler.b (ol3.js:49)
    at ol.MapBrowserEventHandler.ol.events.EventTarget.dispatchEvent (ol3.js:53)
    at ol.MapBrowserEventHandler.<anonymous> (ol3.js:287)
SelectedLinkProperty.js:127 Uncaught ReferenceError: singleLinkSelect is not defined
    at Object.openUnknown (SelectedLinkProperty.js:127)
    at ol.interaction.Select.<anonymous> (LinkPropertyLayer.js:247)
    at ol.interaction.Select.b (ol3.js:49)
    at ol.interaction.Select.ol.events.EventTarget.dispatchEvent (ol3.js:53)
    at ol.interaction.Select.handleEvent (ol3.js:1704)
    at ol.Map.handleMapBrowserEvent (ol3.js:900)
    at ol.MapBrowserEventHandler.b (ol3.js:49)
    at ol.MapBrowserEventHandler.ol.events.EventTarget.dispatchEvent (ol3.js:53)
    at ol.MapBrowserEventHandler.<anonymous> (ol3.js:287)

https://devtest.liikennevirasto.fi/viite/#linkProperty/500130192

**Pull request merged**
