### PR TITLE
Droth 318 fixes to moving of bus stop

### PR DESCRIPTION
**Pull request by leirasf**
Task DROTH-314 and DROTH-318

### CODE REVIEW

**Comment by marquesfm** [comment]
Ok for me

**Comment by oappicgi** [comment]
At least for me it seems  to be failing test "Persist floating on update" in MasstransitStopServiceSpec
with error "Some(1) was not equal to Some(0)"

**Comment by tvenhola** [comment]
Works for me.

**Comment by tvenhola** [comment]
I will now merge master with this.

**Comment by tvenhola** [comment]
This is OK to me

**Pull request merged**
