### PR TITLE
Droth 1109 winter roads need to be filtered out in vvh api

### PR DESCRIPTION
**Pull request by joanacoelho**

### CODE REVIEW

**Comment by oskarmalmstrom** [comment]
ok

**Comment by leirasf** [comment]
We need to be careful with that because VIITE uses the same service with the same enrich methods, so if we want to have some specific for OTH we should extend the roadlinkservice.

**Comment by oskarmalmstrom** [comment]
ok again

**Comment by leirasf** [comment]
Ok

**Pull request merged**
