### PR TITLE
DRVVH-299 Closure date (LAKKAUTUS) on the form has to be <null>, nothing should be shown on the form there

### PR DESCRIPTION
**Pull request by pedrosag**
Altered the from creation to mirror the following behaviour:
If the field LAKKAUTUS value would have no value then it's field will not be included in the form.

### CODE REVIEW

**Comment by JaniKoivisto** [comment]
Should the text 'LAKKAUTUS' still be visible even if we dont have value?

**Comment by Campanha** [comment]
seems fine

**Comment by pedrosag** [comment]
@JaniKoivisto 
Regarding your question about the visibility of the LAKKAUTUS field, from the user story I gathered that it was a field to be removed/hidden from the Form.

I asked on skype if the field would be removed would it be Ok in the future. I was told currently the Viite database does not have that data but the PO hinted that it might have in the future, therefore I made it so that it hides the field if there is no data.

**Comment by leirasf** [comment]
Looks good to me

**Pull request merged**
