### PR TITLE
Droth 331

### PR DESCRIPTION
**Pull request by oappicgi**
Authentication to TR API

Reads username&password from keys.properties file, encodes to base64 and adds to request headers

### CODE REVIEW

**Comment by oappicgi** [comment]
Do not merge until TR  has implemented authentication

**Comment by halied** [comment]
Ok to me

**Comment by tvenhola** [comment]
OK

**Comment by leirasf** [comment]
It looks good

**Comment by tvenhola** [comment]
Waiting for TR implementation

**Pull request merged**
