### PR TITLE
Droth 14 keeping edit mode when jumping objects

### PR DESCRIPTION
**Pull request by pedrosag**
The application no longer resets the "Edit Mode" when transitioning between data views.
Changed each entry in the navigation panel to keep the "Edition Tools" visible if the "Edit Mode" is toggled On.

### CODE REVIEW

**Comment by tvenhola** [comment]
Looks good to me

**Comment by tvenhola** [comment]
A bug: if you're using scissors tool the scissors tool is on when you switch a layer and clicking any road link nags in console log:
`LinearAssetLayer.js:119 Uncaught TypeError: Cannot read property 'distanceObject' of undefined
LinearAssetCutter.cut @ LinearAssetLayer.js:119
clickHandler @ LinearAssetLayer.js:46
triggerEvents @ backbone.js:207
trigger @ backbone.js:148
(anonymous function) @ MapView.js:90
triggerEvent @ Events.js:875
handleBrowserEvent @ Events.js:922
(anonymous function) @ BaseTypes.js:365`

**Comment by tvenhola** [comment]
All tests pass.

**Comment by leirasf** [comment]
Looks good to me

**Pull request merged**
