### PR TITLE
Droth 487 busstops cannot be moved and saved

### PR DESCRIPTION
**Pull request by marquesfm**

### CODE REVIEW

**Comment by marquesfm** [comment]
All ok for me.

**Comment by MAC-CGI** [comment]
Ok, for me

**Comment by tvenhola** [comment]
Looks good, didn't try running yet

**Comment by oappicgi** [comment]
Looks good. (didn't try to run it)

**Comment by joanacoelho** [comment]
ok for me

**Comment by leirasf** [comment]
Looks good to me

**Comment by halied** [comment]
Ok

**Pull request merged**
