### PR TITLE
Drvvh 209

### PR DESCRIPTION
**Pull request by tvenhola**

### CODE REVIEW

**Comment by tvenhola** [comment]
Track code 0 does not show on form

**Comment by tvenhola** [comment]
Fixed showing of missing values, ok for me now.

**Comment by JaniKoivisto** [comment]
According to userstory do we need "staticField('SEGMENTIN ID', 'segmentId')" in form? Otherwise looks good!

**Comment by tvenhola** [comment]
Segment id is a good addition, remove it later if necessary. Now it clears up some confusion there might be.

**Comment by JaniKoivisto** [comment]
Ok

**Pull request merged**
